Event mgmt basic features
bettercallazamat/event-mgmt-ror pull request #2
Opened 2020-05-30 13:28 UTC by bettercallazamat

## Features included in this PR:
1. MVC for event
2. MVC for users
3. Relationship of event and users
4. many-to-many relationship using through for attendance management
5. Basic layout with supportive links to navigate and take actions

2020-05-31 05:04 UTC, wathigo requested changes
### CHANGES REQUIRED
Great work @bettercallazamat  :clap: 
Most requirements have been met.
Let's fix a few issues.
See the comments :point_down: 

**After implementing the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2020-05-31 05:04 UTC, wathigo commented on app/views/events/index.html.erb
> +    <% Event.past.each do |event| %>
Instead of calling `Event.past` in the views we can have 
```ruby
@past_events = Event.past
```
in the index action of the event controller and just use 
```ruby
@past_events.each do |event|
```
in the views.

2020-05-31 05:04 UTC, wathigo commented on app/views/events/index.html.erb
> +    <% Event.upcoming.each do |event| %>
We can also have:
```ruby
@future_events = Event.upcoming
```
in the index action of events controller and just use:
```ruby
@future_event.each do |event|
```
in the views

2020-05-31 05:04 UTC, wathigo commented on app/views/users/show.html.erb
> +<% @user.events.each do |event| %>
**REQUIRED**
* The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-06-01 12:15 UTC, Torres-ssf approved these changes
### Project Approved :+1: :+1: :+1: 
Nice job implementing the requested changes. Your project it's approved.
You can merge the PR now.
Good luck in the next project

Happy coding :computer: 
**Sergio Torres**

2020-06-01 13:01 UTC, merged